---
prometheus_alertmanager_config:
  - static_configs:
    - targets:
      - sg-app:9093

prometheus_targets:
  node:
    - targets:
        - sg-node-1:9100
        - sg-node-2:9100
        - sg-node-3:9100

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"

  - job_name: "nginx"
    metrics_path: /metrics
    static_configs:
      - targets:
          - sg-node-1:9113
          - sg-node-2:9113

  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
